# Generated by Django 3.0.5 on 2020-04-06 16:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('ts', models.DateTimeField(default=datetime.datetime(2020, 4, 6, 16, 28, 22, 507095))),
            ],
            options={
                'db_table': 'parent',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('ts', models.DateTimeField(default=datetime.datetime(2020, 4, 6, 16, 28, 22, 507667))),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='par', to='familytree.Parent')),
            ],
            options={
                'db_table': 'child',
            },
        ),
    ]
