# Generated by Django 3.0.5 on 2020-04-06 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 16, 58, 27, 620333)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 16, 58, 27, 619757)),
        ),
    ]
