# Generated by Django 3.0.5 on 2020-04-06 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0002_auto_20200406_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 24, 8, 519725)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 24, 8, 519272)),
        ),
    ]
