# Generated by Django 3.0.5 on 2020-04-06 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0003_auto_20200406_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 26, 29, 537147)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 26, 29, 536569)),
        ),
    ]
