# Generated by Django 3.0.5 on 2020-04-06 18:42
# hello

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0004_auto_20200406_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='middlename',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 42, 58, 595646)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 42, 58, 595106)),
        ),
    ]
