# Generated by Django 3.0.5 on 2020-04-06 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0005_auto_20200406_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 49, 46, 707672)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 49, 46, 707113)),
        ),
    ]
