# Generated by Django 3.0.5 on 2020-04-06 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0006_auto_20200406_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 19, 15, 33, 714665)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 19, 15, 33, 714093)),
        ),
    ]
